"""add notes to risk_scores

Revision ID: a56dfd1b07a8
Revises: 004_drop_geometry_json
Create Date: 2026-06-03 02:50:49.381575+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a56dfd1b07a8'
down_revision: Union[str, None] = '004_drop_geometry_json'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_case_reports_lga_id'), 'case_reports', ['lga_id'], unique=False)
    op.create_index(op.f('ix_environmental_data_lga_id'), 'environmental_data', ['lga_id'], unique=False)
    op.drop_column('environmental_data', 'data_quality')
    op.create_unique_constraint(None, 'lgas', ['code'])
    op.add_column('risk_scores', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_risk_scores_lga_id'), 'risk_scores', ['lga_id'], unique=False)
    op.drop_column('risk_scores', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scores', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_risk_scores_lga_id'), table_name='risk_scores')
    op.drop_column('risk_scores', 'notes')
    op.drop_constraint(None, 'lgas', type_='unique')
    op.add_column('environmental_data', sa.Column('data_quality', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_environmental_data_lga_id'), table_name='environmental_data')
    op.drop_index(op.f('ix_case_reports_lga_id'), table_name='case_reports')
    # ### end Alembic commands ###
